In [26]:
import numpy as np

# Program One
print("PROGRAM ONE OUTPUT:\n")
arr1 = np.arange(1,16).reshape(3,5)
# Main array
print(arr1, "\n")
# Select Row 2
print(arr1[1], "\n")
# Select the column 4
print(arr1[:,3], "\n")
# Select rows 0 and 1
print(arr1[0:2], "\n")
# Select columns 2–4
print(arr1[:,1:4], "\n")
# Select the element that is in row1 and column4
print(arr1[0,3], "\n")
# Select all elements from rows 1 and 2 that are in columns 0, 2 and 4
print(arr1[0:2,0:5:2], "\n")

# Program Two
print("PROGRAM TWO OUTPUT:\n")
# Main Arrays
array1 = np.array([[0,1],[2,3]])
array2 = np.array([[4,5],[6,7]])
print(array1, "\n")
print(array2, "\n")
# Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
array3 = np.vstack((array1,array2))
print(array3, "\n")
# Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
array4 = np.hstack((array1,array2))
print(array4, "\n")
# Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
array5 = np.vstack((array4,array4))
print(array5, "\n")
# Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.
array6 = np.hstack((array3,array3))
print(array6, "\n")

# Program Three
print("PROGRAM THREE OUTPUT:\n")
# Base 2x2 pattern
tile = np.array([["*","-"], ["-","*"]])
print(tile, "\n")
# 6x6 pattern of the above 2x2 tile.
checkerBoard = np.tile(tile,(6,6))
print(checkerBoard, "\n")

PROGRAM ONE OUTPUT:

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

[ 6  7  8  9 10] 

[ 4  9 14] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]] 

4 

[[ 1  3  5]
 [ 6  8 10]] 

PROGRAM TWO OUTPUT:

[[0 1]
 [2 3]] 

[[4 5]
 [6 7]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[0 1 4 5]
 [2 3 6 7]] 

[[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]] 

[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]] 

PROGRAM THREE OUTPUT:

[['*' '-']
 ['-' '*']] 

[['*' '-' '*' '-' '*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' 