In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
plt.style.use('ggplot')

iris = datasets.load_iris()
x = iris.data
y = iris.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Neural Network (MLP)
scaler = StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)
mlp = MLPClassifier(hidden_layer_sizes=(10,3), max_iter=500, activation='relu', solver='adam', random_state=42)
mlp.fit(x_train_scaled, y_train)
nn_y_prediction = mlp.predict(x_test_scaled)
nn_accuracy = accuracy_score(y_test, nn_y_prediction)
print(f"NN Accuracy: {nn_accuracy}")

# SVM Model
model = SVC(kernel='linear')
model.fit(x_train, y_train)
svm_y_prediction = model.predict(x_test)
svm_accuracy = accuracy_score(y_test, svm_y_prediction)
print(f"SVM Accuracy: {svm_accuracy}")

# Calculate/Plot confusion matrices
nn_cm = confusion_matrix(y_test, nn_y_prediction)
svm_cm = confusion_matrix(y_test, svm_y_prediction)

print(f"NN Confusion Matrix: {nn_cm}")
print(f"SVM Confusion Matrix: {svm_cm}")

# fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# # NN Confusion Matrix
# sns.heatmap(nn_cm, annot=True, fmt="d", cmap="Blues", xticklabels=iris.target_names, yticklabels=iris.target_names, ax=axes[0])
# axes[0].set_title("Neural Network Confusion Matrix")
# axes[0].set_xlabel("Predicted")
# axes[0].set_ylabel("Actual")

# # SVM Confusion Matrix
# sns.heatmap(svm_cm, annot=True, fmt="d", cmap="Oranges", xticklabels=iris.target_names, yticklabels=iris.target_names, ax=axes[1])
# axes[1].set_title("SVM Confusion Matrix")
# axes[1].set_xlabel("Predicted")
# axes[1].set_ylabel("Actual")

plt.tight_layout()
plt.show()

NN Accuracy: 1.0
SVM Accuracy: 1.0
NN Confusion Matrix: [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
SVM Confusion Matrix: [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


*Write a brief summary discussing which model performed better on the Iris dataset and why this might be the case. Include neural network's configurations (hidden layers) details:*

From what I can see, if the neural network is setup in a way that allows it to learn the dataset, they perform about the same. If you limit the number of neurons, hidden layers, or iterations too much the NN models accuracy will suffer. I tried to limit the number of neurons, hidden layers, and iterations while retaining an accuracy score of 1.0. These are the values I came to.

**NN Details:** *mlp = MLPClassifier(hidden_layer_sizes=(10,3), max_iter=500, activation='relu', solver='adam', random_state=42)*

The NN has 10 neurons with three hidden layers. It also has 500 iterations that it will attempt to do. Relu is the activation function used here and Adam is the optimization algorithm.